# Generated by Django 4.2.3 on 2023-07-21 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('is_enrolled', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='newapp',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
